# Databricks Configuration Parameters
databricks:
  # Environment-specific configurations
  environments:
    sandbox:
      host: https://dbc-0c2248b3-6656.cloud.databricks.com
      client_id: 111986ad-4fc6-45b4-9469-e7c7c581cbb6
      client_secret: dose9b72dea76c379efe05c765be4c9bde18  # pragma: allowlist secret
      auth_type: oauth-m2m

    # dev:
    #   host: ${DATABRICKS_HOST_DEV}
    #   client_id: ${DATABRICKS_CLIENT_ID_DEV}
    #   client_secret: ${DATABRICKS_CLIENT_SECRET_DEV}
    #   auth_type: oauth-m2m

    # test:
    #   host: ${DATABRICKS_HOST_TEST}
    #   client_id: ${DATABRICKS_CLIENT_ID_TEST}
    #   client_secret: ${DATABRICKS_CLIENT_SECRET_TEST}
    #   auth_type: oauth-m2m

    # prod:
    #   host: ${DATABRICKS_HOST_PROD}
    #   client_id: ${DATABRICKS_CLIENT_ID_PROD}
    #   client_secret: ${DATABRICKS_CLIENT_SECRET_PROD}
    #   auth_type: oauth-m2m

# OIDC Configuration for GitHub Actions
oidc:
  aws:
    role_arn: arn:aws:iam::125067017412:role/GA-OIDC-admin
    region: us-east-2
    session_name: github-action-session

  github:
    repository: amic-app/da-lakehouse-raw
    ref: refs/heads/main

# Service Principal Mappings
service_principals:
  sandbox: 111986ad-4fc6-45b4-9469-e7c7c581cbb6
  # dev: 111986ad-4fc6-45b4-9469-e7c7c581cbb6
  # test: fb3648e1-7d19-4a94-a4db-5f69eaf8cf8b
  # prod: 6f148b62-472e-40c4-bb1d-35aa176822bf

# AWS Secrets Manager Configuration
secrets:
  databricks_credentials: assetbundle-sandbox-credentials
  service_principal_sandbox: ${SERVICE_PRINCIPAL_SANDBOX_SECRET}

# Bundle Deployment Configuration
deployment:
  default_target: sandbox
  workspace_root: /Workspace/deployment
  bundle_name: da-lakehouse-raw
