# Databricks Configuration Parameters
databricks:
  # Environment-specific configurations
  environments:
    sandbox:
      host: https://dbc-f7a333f8-6cdd.cloud.databricks.com
      client_id: a0a83729-f6b5-4f85-bf22-699bbe7feb6a
      client_secret: dose745470e79abf106e183467d916b68537 # pragma: allowlist secret
      auth_type: oauth-m2m

    dev:
      host: https://amic-enterprise-workspace.cloud.databricks.com
      client_id: eb479c40-27ab-4f3a-90cd-14eafd1f7433
      client_secret: dosec76a7f61f23ab42b966af7c29edb89bb
      auth_type: oauth-m2m

    # test:
    #   host: ${DATABRICKS_HOST_TEST}
    #   client_id: ${DATABRICKS_CLIENT_ID_TEST}
    #   client_secret: ${DATABRICKS_CLIENT_SECRET_TEST}
    #   auth_type: oauth-m2m

    # prod:
    #   host: ${DATABRICKS_HOST_PROD}
    #   client_id: ${DATABRICKS_CLIENT_ID_PROD}
    #   client_secret: ${DATABRICKS_CLIENT_SECRET_PROD}
    #   auth_type: oauth-m2m

# OIDC Configuration for GitHub Actions
oidc:
  aws:
    role_arn: arn:aws:iam::389527410754:role/OIDC-GitHub
    region: eu-north-1
    session_name: github-action-session

  github:
    repository: nandam-hub/da-lakehouse
    ref: refs/heads/main

# Service Principal Mappings
service_principals:
  sandbox: 111986ad-4fc6-45b4-9469-e7c7c581cbb6
  dev: eb479c40-27ab-4f3a-90cd-14eafd1f7433
  # test: fb3648e1-7d19-4a94-a4db-5f69eaf8cf8b
  # prod: 6f148b62-472e-40c4-bb1d-35aa176822bf

# AWS Secrets Manager Configuration
secrets:
  databricks_credentials: databricks-serviceprincipal-dev
  service_principal_sandbox: ${SERVICE_PRINCIPAL_SANDBOX_SECRET}
  service_principal_dev: eb479c40-27ab-4f3a-90cd-14eafd1f7433
  client_secret_dev: dosec76a7f61f23ab42b966af7c29edb89bb

# Bundle Deployment Configuration
deployment:
  default_target: sandbox
  workspace_root: /Workspace/deployment
  bundle_name: da-lakehouse
